### ISSUE TITLE
GUI Implementation

### ISSUE THREAD

**Issue by yashito** [fantaye-1/man_pac#23]
The GUI implementation using GTK.
The windows will be created for each Manpac and the Ghosts that moves.

**Comment by yashito** [comment]
The sample code has been pushed as a name "gtktest.c" with notes in its header.
This will needs to be integrated into the original c files.

**Comment by chase** [comment]
Ended up going with X11 because it didn't require a bunch of configuration.

**Comment by chase** [comment]
Need to implement the window for manpac, but almost done.

**Comment by chase** [comment]
Implemented in c674de7200d6d61b76ed7a2fea0c932e4985dccd.
