### ISSUE TITLE
Numerous idle manpac process created

### ISSUE THREAD

**Issue by yashito** [fantaye-1/man_pac#24]
When manpac process was executed, it created about 120 idle processes of manpac, even after it supposed to be terminated.

**Comment by chase** [comment]
@yashito Did you launch manpac directly instead of using the kernel launcher?

**Comment by chase** [comment]
Worth looking into, but I cannot reproduce this.

**Comment by yashito** [comment]
I restored my snapshot to initial and it's working fine. Sorry about false alarm. You can remove this issue.

**Comment by chase** [comment]
No problem @yashito! That would have been a crazy thing to deal with before the demo, haha.

**Comment by yashito** [comment]
This bug can be reproduced if manpac is called after running "make clean", perhaps because it removed ghost and manpac executables.

**Comment by chase** [comment]
@yashito After running `make clean`, you ran `manpac` directly? Does `make clean` not remove `manpac` from the directory?

**Comment by yashito** [comment]
Only LKM functionality was used to reproduce this bug, not running executables directly. That is, hook up system call using Konami code and calling `man pac` command.

I do aware that `make clean` would remove manpac executable, but somehow `ps` command lists manpac as well as its `printf` output numerous times: "Waiting for Ghosts to initiallize."

**Comment by chase** [comment]
That's really strange. The binary that is called should be in `/tmp` not the local directory, so it shouldn't matter. Maybe removing the kernel module binary is causing this?
Either way, this can be closed since this wouldn't be standard practice.
