### ISSUE TITLE
Does not exit cleanly on restart, module exit not obeyed

### ISSUE THREAD

**Issue by chase** [fantaye-1/man_pac#25]
![image](https://user-images.githubusercontent.com/5411/48578033-a5685380-e8e6-11e8-8fe7-a48aaf0e3466.png)

It seems that the proc hook specifically is causing issues during teardown for a restart.

**Comment by chase** [comment]
96a9f4a14a9c0565a60c4d0bac5f4a56f73bcff8 possibly fixes this, can you try breaking it @yashito?

**Comment by yashito** [comment]
No problem found after trying followings:
- Standard installing of LKM: clean, make, and load.
- Load LKM again without make clean.
- Remove and reinstall LKM manually without using Makefile.

One thing to note is that when terminating manpac while it's running (with Ctrl+C), this still keeps ghosts alive and it appears again when manpac is opened right after, along with the newly created ghosts.

**Comment by chase** [comment]
@yashito To clarify, are you saying that the following order of events is occurring?

1. Terminate manpac while running
  - Ghosts remain (as expected)
2. Run `man pac`
  - New ghosts appear in addition to old ghosts (more than 4, not as expected)
3. Restart or unload the kernel module
  - No error

**Comment by yashito** [comment]
I've confirmed upto your step 2, but not step 3. I don't know what will happen to lingering Ghost processes after unloading module. Restarting OS will have no issue since it wipes out Ghost processes.

**Comment by chase** [comment]
@yashito Ah, okay. That's a different issue then. Could you put that in a new bug issue.
